name: intra
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bouncing_widget: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.18
  html_parser_plus: ^0.0.1
  http: ^0.13.5
  iconsax: ^0.0.8
  provider: ^6.0.5
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/epitechlogo.png"
#   min_sdk_android: 21
#   web:
#     generate: true
#     image_path: "assets/images/epitechlogo.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/images/epitechlogo.png"
#     icon_size: 48
#   macos:
#     generate: true
#     image_path: "assets/images/epitechlogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: IntraIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
